/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { functionToolChoiceSchema } from "./functionToolChoiceSchema.ts";
import { toolChoiceValueEnumSchema } from "./toolChoiceValueEnumSchema.ts";

export const allowedToolChoiceSchema = z.object({
  type: z.enum(["allowed_tools"]).default("allowed_tools"),
  tools: z.array(z.lazy(() => functionToolChoiceSchema)),
  mode: z.lazy(() => toolChoiceValueEnumSchema),
});
