/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { compactResourceSchema } from "./compactResourceSchema.ts";
import { compactResponseMethodPublicBodySchema } from "./compactResponseMethodPublicBodySchema.ts";

/**
 * @description Success
 */
export const compactResponse200Schema = z.lazy(() => compactResourceSchema);

export const compactResponseMutationRequestSchema = z.lazy(() => compactResponseMethodPublicBodySchema);

export const compactResponseMutationResponseSchema = z.lazy(() => compactResponse200Schema);
