/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { compactionBodySchema } from "./compactionBodySchema.ts";
import { functionCallOutputSchema } from "./functionCallOutputSchema.ts";
import { functionCallSchema } from "./functionCallSchema.ts";
import { messageSchema } from "./messageSchema.ts";
import { reasoningBodySchema } from "./reasoningBodySchema.ts";

/**
 * @description An item representing a message, tool call, tool output, reasoning, or other response element.
 */
export const itemFieldSchema = z
  .union([
    z.lazy(() => messageSchema),
    z.lazy(() => functionCallSchema),
    z.lazy(() => functionCallOutputSchema),
    z.lazy(() => reasoningBodySchema),
    z.lazy(() => compactionBodySchema),
  ])
  .describe("An item representing a message, tool call, tool output, reasoning, or other response element.");
