/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { reasoningEffortEnumSchema } from "./reasoningEffortEnumSchema.ts";
import { reasoningSummaryEnumSchema } from "./reasoningSummaryEnumSchema.ts";

/**
 * @description **gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
 */
export const reasoningParamSchema = z
  .object({
    effort: z.optional(z.union([z.lazy(() => reasoningEffortEnumSchema), z.null()])),
    summary: z.optional(z.union([z.lazy(() => reasoningSummaryEnumSchema).and(z.any()), z.null()])),
  })
  .describe(
    "**gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).",
  );
