/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { reasoningEffortEnumSchema } from "./reasoningEffortEnumSchema.ts";
import { reasoningSummaryEnumSchema } from "./reasoningSummaryEnumSchema.ts";

/**
 * @description Reasoning configuration and metadata that were used for the response.
 */
export const reasoningSchema = z
  .object({
    effort: z.union([z.lazy(() => reasoningEffortEnumSchema), z.null()]),
    summary: z.union([z.lazy(() => reasoningSummaryEnumSchema).and(z.any()), z.null()]),
  })
  .describe("Reasoning configuration and metadata that were used for the response.");
