/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { functionToolParamSchema } from "./functionToolParamSchema.ts";

export const responsesToolParamSchema = z.lazy(() => functionToolParamSchema);
