/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { jsonSchemaResponseFormatParamSchema } from "./jsonSchemaResponseFormatParamSchema.ts";
import { textResponseFormatSchema } from "./textResponseFormatSchema.ts";

export const textFormatParamSchema = z.union([
  z.lazy(() => textResponseFormatSchema),
  z.lazy(() => jsonSchemaResponseFormatParamSchema),
]);
