/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { functionToolSchema } from "./functionToolSchema.ts";

/**
 * @description A tool that can be used to generate a response.
 */
export const toolSchema = z.lazy(() => functionToolSchema).describe("A tool that can be used to generate a response.");
