import { describe, expect, test } from "bun:test";
import {
  MCP_DRAFT_PROTOCOL_VERSION,
  MCP_LEGACY_2024_11_PROTOCOL_VERSION,
  MCP_RELEASED_PROTOCOL_VERSION,
  McpClient,
  McpClientError,
  type McpClientTransport,
  type McpClientTransportHandlers,
} from "../../../src/infrastructure/mcp/client";
import { JSON_RPC_VERSION, type JsonRpcOutgoingMessage, type JsonRpcRequest } from "../../../src/infrastructure/mcp/json-rpc";
import { McpTransportError } from "../../../src/infrastructure/mcp/transport";
import type { McpServerConfig } from "../../../src/infrastructure/mcp/types";

describe("MCP client lifecycle", () => {
  test("modern discover success chooses protocol and sends per-request meta", async () => {
    const transport = new ScriptedTransport({
      "server/discover": () => ({
        protocolVersions: [MCP_DRAFT_PROTOCOL_VERSION, MCP_RELEASED_PROTOCOL_VERSION],
        capabilities: { tools: { listChanged: true } },
        serverInfo: { name: "modern-server" },
      }),
      "tools/list": (request) => {
        expect(request.params).toMatchObject({
          _meta: {
            protocolVersion: MCP_DRAFT_PROTOCOL_VERSION,
            clientInfo: { name: "soba-agent" },
          },
        });
        return { tools: [{ name: "echo", description: "Echo" }] };
      },
    });
    const client = createClient(transport);

    await client.start();
    const tools = await client.listTools();

    expect(client.getState()).toMatchObject({
      state: "ready",
      lifecycle: "modern",
      protocolVersion: MCP_DRAFT_PROTOCOL_VERSION,
      capabilities: { tools: { listChanged: true } },
      serverInfo: { name: "modern-server" },
    });
    expect(tools).toEqual([{ name: "echo", description: "Echo" }]);
    expect(transport.methods()).toEqual(["server/discover", "tools/list"]);
  });

  test("legacy initialize fallback succeeds when server/discover is unsupported", async () => {
    const transport = new ScriptedTransport({
      "server/discover": () => {
        throw jsonRpcError(-32601, "Method not found");
      },
      initialize: () => ({
        protocolVersion: MCP_RELEASED_PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: { name: "legacy-server" },
      }),
    });
    const client = createClient(transport);

    await client.start();

    expect(client.getState()).toMatchObject({
      state: "ready",
      lifecycle: "legacy",
      protocolVersion: MCP_RELEASED_PROTOCOL_VERSION,
      serverInfo: { name: "legacy-server" },
    });
    expect(transport.methods()).toEqual(["server/discover", "initialize", "notifications/initialized"]);
  });

  test("legacy initialize accepts 2024-11-05 servers generated by minimal stdio fixtures", async () => {
    const transport = new ScriptedTransport({
      "server/discover": () => {
        throw jsonRpcError(-32601, "Method not found");
      },
      initialize: () => ({
        protocolVersion: MCP_LEGACY_2024_11_PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: { name: "legacy-2024-server" },
      }),
      "tools/list": () => ({
        tools: [{ name: "repo_summary", description: "Repository summary" }],
      }),
    });
    const client = createClient(transport);

    await client.start();
    const tools = await client.listTools();

    expect(client.getState()).toMatchObject({
      state: "ready",
      lifecycle: "legacy",
      protocolVersion: MCP_LEGACY_2024_11_PROTOCOL_VERSION,
      serverInfo: { name: "legacy-2024-server" },
    });
    expect(tools).toEqual([{ name: "repo_summary", description: "Repository summary" }]);
    expect(transport.methods()).toEqual(["server/discover", "initialize", "notifications/initialized", "tools/list"]);
  });

  test("incompatible protocol is a controlled startup error", async () => {
    const transport = new ScriptedTransport({
      "server/discover": () => ({
        protocolVersions: ["1999-01-01"],
        capabilities: { tools: {} },
      }),
    });
    const client = createClient(transport);

    await expect(client.start()).rejects.toMatchObject({
      name: "McpClientError",
      code: "incompatible_protocol",
    });
    expect(client.getState()).toMatchObject({
      state: "degraded",
      lifecycle: null,
    });
  });

  test("missing tools capability is a controlled degraded startup error", async () => {
    const transport = new ScriptedTransport({
      "server/discover": () => ({
        protocolVersions: [MCP_DRAFT_PROTOCOL_VERSION],
        capabilities: { resources: {} },
      }),
    });
    const client = createClient(transport);

    await expect(client.start()).rejects.toMatchObject({
      code: "missing_capability",
    });
    expect(client.getState().state).toBe("degraded");
  });

  test("tools/list single page returns tools deterministically", async () => {
    const transport = readyModernTransport({
      "tools/list": () => ({
        tools: [{ name: "read_file", inputSchema: { type: "object" } }],
      }),
    });
    const client = createClient(transport);
    await client.start();

    await expect(client.listTools()).resolves.toEqual([{ name: "read_file", inputSchema: { type: "object" } }]);
  });

  test("tools/list supports pagination", async () => {
    const transport = readyModernTransport({
      "tools/list": (request) => {
        const cursor = isRecord(request.params) && typeof request.params.cursor === "string" ? request.params.cursor : null;
        if (!cursor) {
          return { tools: [{ name: "first" }], nextCursor: "page-2" };
        }

        return { tools: [{ name: "second" }] };
      },
    });
    const client = createClient(transport);
    await client.start();

    const tools = await client.listTools();

    expect(tools.map((tool) => tool.name)).toEqual(["first", "second"]);
    expect(transport.methods()).toEqual(["server/discover", "tools/list", "tools/list"]);
  });

  test("tools/call success preserves modern result metadata", async () => {
    const transport = readyModernTransport({
      "tools/call": (request) => {
        expect(request.params).toMatchObject({
          name: "echo",
          arguments: { value: 1 },
          _meta: {
            protocolVersion: MCP_DRAFT_PROTOCOL_VERSION,
          },
        });
        return {
          content: [{ type: "text", text: "ok" }],
          structuredContent: { value: 1 },
          resultType: "structured",
          ttlMs: 1_000,
          cacheScope: "session",
          isError: false,
        };
      },
    });
    const client = createClient(transport);
    await client.start();

    await expect(client.callTool("echo", { value: 1 })).resolves.toEqual({
      content: [{ type: "text", text: "ok" }],
      structuredContent: { value: 1 },
      resultType: "structured",
      ttlMs: 1_000,
      cacheScope: "session",
      isError: false,
    });
  });

  test("tools/call timeout rejects with controlled error", async () => {
    const transport = readyModernTransport({
      "tools/call": () => ScriptedTransport.noResponse,
    });
    const client = createClient(transport, { requestTimeoutMs: 5 });
    await client.start();

    await expect(client.callTool("slow", {}, { timeoutMs: 5 })).rejects.toMatchObject({
      name: "McpClientError",
      code: "request_failed",
    });
    expect(client.getState().state).toBe("ready");
  });

  test("tools/call cancellation rejects with controlled error", async () => {
    const transport = readyModernTransport({
      "tools/call": () => ScriptedTransport.noResponse,
    });
    const controller = new AbortController();
    const client = createClient(transport, { requestTimeoutMs: 100 });
    await client.start();

    const result = client.callTool("slow", {}, { signal: controller.signal });
    controller.abort();

    await expect(result).rejects.toMatchObject({
      name: "McpClientError",
      code: "request_failed",
    });
    expect(client.getState().state).toBe("ready");
  });

  test("tools list-changed notification invalidates cache", async () => {
    let listCount = 0;
    const transport = readyModernTransport({
      "tools/list": () => {
        listCount += 1;
        return { tools: [{ name: `tool-${listCount}` }] };
      },
    });
    const client = createClient(transport);
    await client.start();

    expect((await client.listTools()).map((tool) => tool.name)).toEqual(["tool-1"]);
    expect((await client.listTools()).map((tool) => tool.name)).toEqual(["tool-1"]);

    client.receive({
      jsonrpc: JSON_RPC_VERSION,
      method: "notifications/tools/list_changed",
    });

    expect(client.getState().toolsListChanged).toBe(true);
    expect((await client.listTools()).map((tool) => tool.name)).toEqual(["tool-2"]);
    expect(client.getState().toolsListChanged).toBe(false);
  });

  test("transport crash moves client to crashed state", async () => {
    const transport = readyModernTransport();
    const client = createClient(transport);
    await client.start();

    transport.crash(new Error("process exited 42"));

    expect(client.getState()).toMatchObject({
      state: "crashed",
      lastError: "process exited 42",
      lastErrorCode: "process_exit",
    });
    await expect(client.listTools()).rejects.toBeInstanceOf(McpClientError);
  });
});

type HandlerResult = unknown | typeof ScriptedTransport.noResponse;
type RequestHandler = (request: JsonRpcRequest) => HandlerResult;

class ScriptedTransport implements McpClientTransport {
  static readonly noResponse = Symbol("no-response");

  readonly kind = "memory";
  private onEvent: McpClientTransportHandlers | null = null;
  private readonly requestHandlers: Record<string, RequestHandler>;
  private started = false;
  readonly sent: JsonRpcOutgoingMessage[] = [];

  constructor(requestHandlers: Record<string, RequestHandler>) {
    this.requestHandlers = requestHandlers;
  }

  attach(onEvent: McpClientTransportHandlers): McpClientTransport {
    this.onEvent = onEvent;
    return this;
  }

  start(): void {
    this.started = true;
  }

  send(message: JsonRpcOutgoingMessage): void {
    if (!this.started) {
      throw new Error("transport not started");
    }

    this.sent.push(message);
    if (!("method" in message)) {
      return;
    }
    if (!("id" in message)) {
      return;
    }

    const handler = this.requestHandlers[message.method];
    if (!handler) {
      this.onEvent?.({
        type: "message",
        message: {
        jsonrpc: JSON_RPC_VERSION,
        id: message.id,
        error: {
          code: -32601,
          message: "Method not found",
        },
        },
      });
      return;
    }

    try {
      const result = handler(message);
      if (result === ScriptedTransport.noResponse) {
        return;
      }

      this.onEvent?.({
        type: "message",
        message: {
        jsonrpc: JSON_RPC_VERSION,
        id: message.id,
        result,
        },
      });
    } catch (error) {
      const rpcError = isJsonRpcErrorLike(error) ? error : jsonRpcError(-32603, error instanceof Error ? error.message : String(error));
      this.onEvent?.({
        type: "message",
        message: {
        jsonrpc: JSON_RPC_VERSION,
        id: message.id,
        error: rpcError,
        },
      });
    }
  }

  async shutdown(): Promise<void> {
    this.started = false;
  }

  close(): Promise<void> {
    return this.shutdown();
  }

  diagnostics() {
    return {
      kind: this.kind,
      state: this.started ? "running" : "closed",
    } as const;
  }

  crash(error: unknown): void {
    this.onEvent?.({
      type: "error",
      error: new McpTransportError("process_exit", error instanceof Error ? error.message : String(error), {
        kind: "memory",
        cause: error,
      }),
    });
  }

  methods(): string[] {
    return this.sent.filter((message): message is JsonRpcRequest => "method" in message).map((message) => message.method);
  }
}

function createClient(
  transport: ScriptedTransport,
  options: {
    requestTimeoutMs?: number;
  } = {},
): McpClient {
  return new McpClient({
    server: testServerConfig(),
    transportFactory: (handlers) => transport.attach(handlers),
    requestTimeoutMs: options.requestTimeoutMs ?? 50,
  });
}

function readyModernTransport(handlers: Record<string, RequestHandler> = {}): ScriptedTransport {
  return new ScriptedTransport({
    "server/discover": () => ({
      protocolVersions: [MCP_DRAFT_PROTOCOL_VERSION],
      capabilities: { tools: { listChanged: true } },
      serverInfo: { name: "ready-modern" },
    }),
    ...handlers,
  });
}

function testServerConfig(): McpServerConfig {
  return {
    id: "test",
    name: "Test MCP",
    transport: "stdio",
    command: "bun",
    args: [],
    env: {},
    cwd: "/tmp",
    timeoutMs: 50,
    maxOutputBytes: 1024,
    trustMode: "normal",
    enabled: true,
  };
}

function jsonRpcError(code: number, message: string): { code: number; message: string } {
  return { code, message };
}

function isJsonRpcErrorLike(value: unknown): value is { code: number; message: string } {
  return isRecord(value) && typeof value.code === "number" && typeof value.message === "string";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
