/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { urlCitationBodySchema } from "./urlCitationBodySchema.ts";

/**
 * @description An annotation that applies to a span of output text.
 */
export const annotationSchema = z
  .lazy(() => urlCitationBodySchema)
  .describe("An annotation that applies to a span of output text.");
