/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { createResponseBodySchema } from "./createResponseBodySchema.ts";
import { responseResourceSchema } from "./responseResourceSchema.ts";

/**
 * @description Success
 */
export const createResponse200Schema = z
  .lazy(() => responseResourceSchema)
  .describe("The complete response object that was returned by the Responses API.");

export const createResponseMutationRequestSchema = z.lazy(() => createResponseBodySchema);

export const createResponseMutationResponseSchema = z.lazy(() => createResponse200Schema);
