/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { topLogProbSchema } from "./topLogProbSchema.ts";

/**
 * @description The log probability of a token.
 */
export const logProbSchema = z
  .object({
    token: z.string(),
    logprob: z.number(),
    bytes: z.array(z.number().int()),
    top_logprobs: z.array(z.lazy(() => topLogProbSchema).describe("The top log probability of a token.")),
  })
  .describe("The log probability of a token.");
