/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { annotationSchema } from "./annotationSchema.ts";
import { logProbSchema } from "./logProbSchema.ts";

/**
 * @description A text output from the model.
 */
export const outputTextContentSchema = z
  .object({
    type: z.enum(["output_text"]).default("output_text").describe("The type of the output text. Always `output_text`."),
    text: z.string().describe("The text output from the model."),
    annotations: z
      .array(z.lazy(() => annotationSchema).describe("An annotation that applies to a span of output text."))
      .describe("The annotations of the text output."),
    logprobs: z.optional(z.array(z.lazy(() => logProbSchema).describe("The log probability of a token."))),
  })
  .describe("A text output from the model.");
