/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { specificFunctionParamSchema } from "./specificFunctionParamSchema.ts";

export const specificToolChoiceParamSchema = z.lazy(() => specificFunctionParamSchema);
