/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { textFormatParamSchema } from "./textFormatParamSchema.ts";
import { verbosityEnumSchema } from "./verbosityEnumSchema.ts";

export const textParamSchema = z.object({
  format: z.optional(
    z.union([z.lazy(() => textFormatParamSchema), z.null()]).describe("The format configuration for text output."),
  ),
  verbosity: z.optional(z.lazy(() => verbosityEnumSchema).and(z.any())),
});
