/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { jsonObjectResponseFormatSchema } from "./jsonObjectResponseFormatSchema.ts";
import { jsonSchemaResponseFormatSchema } from "./jsonSchemaResponseFormatSchema.ts";
import { textResponseFormatSchema } from "./textResponseFormatSchema.ts";
import { verbosityEnumSchema } from "./verbosityEnumSchema.ts";

export const textFieldSchema = z.object({
  format: z.union([
    z.lazy(() => textResponseFormatSchema),
    z.lazy(() => jsonObjectResponseFormatSchema),
    z.lazy(() => jsonSchemaResponseFormatSchema),
  ]),
  verbosity: z.optional(z.lazy(() => verbosityEnumSchema)),
});
